### ISSUE TITLE
Merge hosts from other lists?

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/adblock#10]
I just discovered that one: https://adaway.org/hosts.txt

I don't know if there are new hosts compared to hosts zero but that might be interesting to check.

Do you know any other list?

**Comment by MattiSG** [comment]
Well, there are those listed in https://github.com/AdAway/AdAway/wiki/HostsSources… and the gold standard, which actually already does merging, would probably be https://github.com/StevenBlack/hosts.

Oh, and I really like this one too: https://github.com/gasull/adblock-nsa  :wink:

So:

1. Should `adblock` default to https://github.com/StevenBlack/hosts?
2. Should `adblock` support a `--source` option to which one could provide an URL from which the host file is fetched?
3. Should the `--source` option accept multiple sources and merge them?

**Comment by MattiSG** [comment]
Actually, option 4: #11  :wink:

**Comment by davidbgk** [comment]
Heh https://github.com/gasull/adblock-nsa ❤️

**Comment by MattiSG** [comment]
I actually submitted it to Dan —we'll see if it makes it to the standard hosts file  :wink:
