### ISSUE TITLE
Retire software?

### ISSUE THREAD

**Issue by MattiSG** [MattiSG/adblock#11]
Should `adblock` be retired, and suggest switching to https://github.com/StevenBlack/hosts? It seems to have almost all of the features of this piece of software, and more.

What is missing:

- Updates autodetection. _Ok, I can live with that._
- Ability to switch off the blocks in one line. _That's annoying._

**Comment by davidbgk** [comment]
I'm not sure if the merge is really pertinent. If we take my favorite host (`google-analytics`), the file once merged contains multiple entries. The ones commented out from http://someonewhocares.org/hosts/zero/ but also entries still active from other sources.

As you mentioned earlier, given the number of sites broken when you block analytics (so sad…) you don't want to multi-edit the hosts file manually each time you want to access that content.

This is something I should discuss upstream but it's just my initial gut feeling with the project.

**Comment by davidbgk** [comment]
Alright, I just read the doc and my case is made possible [via white listing](https://github.com/StevenBlack/hosts#how-do-i-prevent-domains-from-being-included), nice!

**Comment by MattiSG** [comment]
The `adblock` piece of software only manages downloading, updating and reverting a hosts file. It trusts an external source (currently Dan Pollock's hosts file) for listing the domains.
The referenced https://github.com/StevenBlack/hosts today only merges and consolidates several sources into a single hosts file.

So really, they are complementary rather than competitive 🙂 

One could suggest to switch to the consolidated ads + malware source hosts file from https://github.com/StevenBlack/hosts, or that some combinatories are suggested for installation by `adblock`, since https://github.com/StevenBlack/hosts offers options beyond ads and malware: fakenews, gambling, porn, social. This is not a need I have at the moment: Dan Pollock's file fits my needs.
