### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by mehedeetalha** [MattiSG/adblock#15]
Please update the files to new one

**Comment by MattiSG** [comment]
Hi @mehedeetalha!

I'm not sure what you mean. Whenever you execute `adblock`, it will check for updates in the blocklist and update it if necessary. If you start seeing ads again, just run `sudo adblock`; if after that you still see ads, identify the domain that serves them and send a request to Dan Pollock at hosts@someonewhocares.org 🙂

Please let me know if that answers your need.

**Comment by kuwaitbinary** [comment]
Can we add multiple ads list host like GoodByeAds, AdAway, etc ?

**Comment by MattiSG** [comment]
This issue should have been closed.

The comment above is a separate topic that should be open in its own, separate issue. Quick reply to @kuwaitbinary: no, at this stage this script does not support multiple sources. In my experience, the accuracy in blocking of the current file is completely satisfactory. I am thus not certain what would be the gain in adding more lists.
If you find that the results are unsatisfactory, please open another issue providing a few examples of domains that are not blocked with the current source and that would be blocked properly by including other sources 🙂
