### ISSUE TITLE
Support customized list?

### ISSUE THREAD

**Issue by junwei-wang** [MattiSG/adblock#16]
Do you think it would be interesting to extend your script to add a list of domains from the user side.

**Comment by MattiSG** [comment]
Hi @junwei-wang! Thanks for your message 🙂 

I'm not sure I fully understand your suggestion. This script already keeps the existing lists on the system's hosts file. If you have a list of domains and you add it to your hosts file, it will be merged with the blocklist 🙂

This is mentioned in the README:

> This will merge the blocklist with your current hostsfile, so any local adjustments you had made previously are still active.

Maybe this is not clear enough.

Does this feature cover your suggestion? How could we make the documentation clearer? 🙂

**Comment by junwei-wang** [comment]
It is clear enough. Thank you.
