### ISSUE TITLE
Mention complementary browser blocking

### ISSUE THREAD

**Issue by MattiSG** [MattiSG/adblock#5]
Alternative: https://www.eff.org/privacybadger

**Comment by MattiSG** [comment]
Ghostery does a good job and complementing `adblock`.

**Comment by davidbgk** [comment]
On that topic, I use both ghostery and umatrix. I think that it's somehow redundant with adblock and I don't want to let hosts’ filtering on the browser side when it can be achieved (I guess faster) by the system. What are your thoughts about that?

**Comment by MattiSG** [comment]
https://github.com/MattiSG/adblock#is-it-enough  :wink:

**Comment by davidbgk** [comment]
It's interesting when you use LittleSnitch to see that Slack channels are tracked via GAnalytics too ;)
