### ISSUE TITLE
Add the ability to install it via homebrew

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/adblock#7]
For lazy guys like me, `brew install adblock` would be great :)

**Comment by joelpurra** [comment]
@MattiSG: I'd prefer to see a tap! This way users could also be notified when there's an update -- and even have it automatically installed.

I maintain a tap with my own software, and It's not "hard" -- in part because I've chosen to rely on git and git tags instead of urls and sha256 hashes.
https://github.com/joelpurra/homebrew-joelpurra

**Comment by MattiSG** [comment]
Thanks @joelpurra! After some struggles with brew documentation, I should have a working tap documented in the [`brew-tap`](https://github.com/MattiSG/adblock/tree/brew-tap) branch  :)

Could you (and possibly @davidbgk) check if everything goes well with `/usr/local/bin/adblock && brew tap mattisg/mattisg && brew install adblock`?  :)

**Comment by joelpurra** [comment]
@MattiSG: Glad to see a tap -- hope it wasn't too much work =)

Below is my shell output. Note that I initially installed adblock without `sudo`. The conclusion is that switching to `brew` works well, as `brew` hints to using both `rm ...` and `brew link ...`.

```bash
brew tap mattisg/mattisg
```

```text
==> Tapping mattisg/mattisg
Cloning into '/usr/local/Library/Taps/mattisg/homebrew-mattisg'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Tapped 1 formula (29 files, 120K)
```

```bash
brew install adblock
```

```text
==> Installing adblock from mattisg/homebrew-mattisg
==> Cloning https://github.com/mattisg/adblock.git
Cloning into '/Library/Caches/Homebrew/adblock--git'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Note: checking out '08c8f827b0b752a0ca3538e3a0bc90309b123579'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag v1.0.1
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/adblock
Target /usr/local/bin/adblock
already exists. You may want to remove it:
  rm '/usr/local/bin/adblock'

To force the link and overwrite all conflicting files:
  brew link --overwrite adblock

To list all files that would be deleted:
  brew link --overwrite --dry-run adblock

Possible conflicting files are:
/usr/local/bin/adblock
==> Summary
🍺  /usr/local/Cellar/adblock/1.0.1: 3 files, 12K, built in 2 seconds
```

```bash
rm '/usr/local/bin/adblock'
```

```bash
brew install adblock
```

```text
Warning: mattisg/mattisg/adblock-1.0.1 already installed, it's just not linked
```

```bash
brew link adblock
```

```text
Linking /usr/local/Cellar/adblock/1.0.1... 1 symlinks created
```

**Comment by MattiSG** [comment]
Great, thanks for the test!  :)

> hope it wasn't too much work

It was more than expected, partly because I couldn't find any reference on `install_symlink` vs `install`, and none on whether I could add some `uninstall` hooks… But thanks again for your pointers, I've learned something  :)

**Comment by davidbgk** [comment]
I confirm that it works too! 👍
